### ISSUE TITLE
[discussion] use transforms in potential_fn

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#107]
I would like to suggest a way to use support information for default transforms and incorporate it in potential_fn:
+ initialize_model takes an additional argument named transforms, which is a dict map each latent variable to its user-defined transform. Otherwise, we use the default transform.
+ initialize model returns a z transform fn (in addition to init unconstrained param and potential_fn) for tranforming unconstrained variables to contrained variable. So users can use this transform fn in transform argument of tscan: `tscan(..., transform=lambda latent: z_tranform_fn(latent.z))`

**Comment by neerajprad** [comment]
We could handle the default transforms for both SVI and MCMC via an effect handler, the only difference being that for SVI it affects only the `param` statements whereas for MCMC it would transform `sample` statements. Another thing to note is that just transforming in the outside loop is not be enough, since this also changes the PE computation.

Regarding:
> initialize_model takes an additional argument named transforms.

In practice, I haven't seen models where users had to override the default transforms. I can imagine that providing a way to use custom transforms might be useful for certain models. If we provide that, it shouldn't come at the cost of users having to write boiler-plate code for models where they would just use the default transforms anyway. Let me put up something, and we can discuss the interface issues in the PR.

**Comment by neerajprad** [comment]
Actually, on second thoughts, I think your approach above would be the simplest since HMC in numpyro doesn't have access to the model directly.
