### ISSUE TITLE
Mixed HMC 5000x slower on GPU than CPU

### ISSUE THREAD

**Issue by JGameCreation** [pyro-ppl/numpyro#1073]
Hi, I'm currently trying to understand how hardware acceleration works with Jax and NumPyro and observed a few things that appear very weird to me.
I want to run the Mixed HMC code example from the docs with 32 chains:
```
    from jax import random, devices
    import jax.numpy as jnp
    import numpyro
    import numpyro.distributions as dist
    from numpyro.infer import HMC, MCMC, MixedHMC
    numpyro.set_host_device_count(32)
    print(devices())
    def model(probs, locs):
        c = numpyro.sample("c", dist.Categorical(probs))
        numpyro.sample("x", dist.Normal(locs[c], 0.5))

    probs = jnp.array([0.15, 0.3, 0.3, 0.25])
    locs = jnp.array([-2, 0, 2, 4])
    kernel = MixedHMC(HMC(model, trajectory_length=1.2), num_discrete_updates=20)
    mcmc = MCMC(kernel, num_warmup=1000, num_samples=100000, num_chains=32)
    mcmc.run(random.PRNGKey(0), probs, locs)
    mcmc.print_summary()  
    samples = mcmc.get_samples()
    assert "x" in samples and "c" in samples
    assert abs(jnp.mean(samples["x"]) - 1.3) < 0.1
    assert abs(jnp.var(samples["x"]) - 4.36) < 0.5
```
Without `numpyro.set_host_device_count(32)` this takes 33 seconds per chain. But when I add that statement it not only runs the 32 chains in parallel but it also suddenly compiles them so they take only 5 seconds. Why isn't this also compiled for a single chain and how can I do this manually? 
However, it only got really confusing when I set the Jax default device to my RTX 2080 Ti GPU:
```
    import jax
    print(jax.devices()) # It only uses the GPU when I add this line. Why?
    from jax import random
    import jax.numpy as jnp
    import numpyro
    import numpyro.distributions as dist
    from numpyro.infer import HMC, MCMC, MixedHMC
    # numpyro.set_host_device_count(32)
    print(jax.devices())
    def model(probs, locs):
        c = numpyro.sample("c", dist.Categorical(probs))
        numpyro.sample("x", dist.Normal(locs[c], 0.5))
    probs = jax.device_put(jnp.array([0.15, 0.3, 0.3, 0.25]), jax.devices()[0])
    print(probs, probs.device_buffer.device())
    locs = jax.device_put(jnp.array([-2, 0, 2, 4]), jax.devices()[0])
    print(locs, locs.device_buffer.device())
    kernel = MixedHMC(HMC(model, trajectory_length=1.2), num_discrete_updates=20)
    mcmc = MCMC(kernel, num_warmup=1000, num_samples=100000, num_chains=32)
    mcmc.run(random.PRNGKey(0), probs, locs)
    mcmc.print_summary()  
    samples = mcmc.get_samples()
    assert "x" in samples and "c" in samples
    assert abs(jnp.mean(samples["x"]) - 1.3) < 0.1
    assert abs(jnp.var(samples["x"]) - 4.36) < 0.5
```
First of all, the GPU is only detected when I print my devices right after importing Jax. Secondly, unlike my GPU it can only run one chain in parallel. I tried `chain_method='vectorized'` but got `ValueError: too many values to unpack (expected 2)`. But the most confusing this is that even running a single chain on the GPU takes 12-14 minutes! The GPU utilization is at 35% so the GPU is definitely doing something. I know this a very small probabilistic program so some GPU overhead is to be expected but this seems too much.

**Comment by fehiepsi** [comment]
Hi @JGameCreation, I don't think MixedHMC is designed to take advantage of GPU so the slowness is understandable to me. Here I'll just try to explain some of your concerns:
+ Without setting the number of devices to `32`, the `chain_method="sequential"` strategy will be used (otherwise, `"parallel"` method will be used. NumPyro compiles the program in both methods, but in different ways: with "parallel" the whole MCMC sampling process will be compiled, with "sequential + progress_bar=True" only 1 MCMC step is compiled, with "sequential + progress_bar=False" the whole MCMC sampling process will be compiled.
+ If you use NumPyro master branch `pip install -q numpyro@git+https://github.com/pyro-ppl/numpyro`, GPU will be used by default.
+ Currently, we didn't support `vectorized` method for a few MCMC kernels (e.g. in [BarkerMH](https://github.com/pyro-ppl/numpyro/blob/77be4d8171b0570bcabbebf1456f70ef94f9d0e8/numpyro/infer/barker.py#L172)). We should raise a similar error for MixedHMC. Please make a feature request if you want to have that support. But I think you can test first with something like
```python
def get_samples(rng_key):
    mcmc = MCMC(...)
    mcmc.run(rng_key)
    return mcmc.get_samples()

chain_samples = jax.vmap(get_samples)(rng_keys)
```
to see if you actually get benefits GPU.

**Comment by JGameCreation** [comment]
Hi, thanks for your explanations! I tried your suggestion for vectorization and it works as long as I disable the progress bar. It's definitely much faster than running the chains sequentially. If full support for `vectorized` was implemented, would you expect it to be significantly faster than this simple method? I think I'll definitely make a feature request.

**Comment by fehiepsi** [comment]
Thanks for the feedback! Yeah, I think supporting `vectorized` method is not complicated. Let's make further discussion in #1805.
