### ISSUE TITLE
[FR] add format_shapes method to trace

### ISSUE THREAD

**Issue by bdatko** [pyro-ppl/numpyro#1104]
Having `trace.format_shapes()` as in [Pyro](https://docs.pyro.ai/en/stable/poutine.html?highlight=format_shapes#pyro.poutine.Trace.format_shapes) would help with debugging and verifying models, especially with enumeration, as shown in the [Pyro tutorial](https://pyro.ai/examples/tensor_shapes.html#Broadcasting-to-allow-parallel-enumeration).

**Comment by tcbegley** [comment]
@fehiepsi unlike Pyro the trace object in NumPyro is an `OrderedDict` rather than a custom class, so seems to me there's a choice to be made here:

* Create a utility function that takes a trace as input and returns the table of shapes
* Create a custom trace object (probably subclassing `OrderedDict` in the first instance to minimise changes?) and define a `format_shapes` method.

Do you have a preference out of these two, or even a preferred third option?

**Comment by fritzo** [comment]
👍for a utility function.

**Comment by fehiepsi** [comment]
Yes, a utility function would be nice. A third option is to have a handler that adds `print` effect to each sample site. :)
