### ISSUE TITLE
Allow for `high` in TruncatedNormal, TruncatedCauchy

### ISSUE THREAD

**Issue by MarcoGorelli** [pyro-ppl/numpyro#1112]
TruncatedDistribution has both `low` and `high`. Why do `TruncatedNormal` and `TruncatedCauchy` only have `low`?

**Comment by fehiepsi** [comment]
Hi @MarcoGorelli, the reason is currently, the signatures of `TruncatedNormal` is `low, loc, scale`, so introducing `low, high, loc, scale` will break current user codes. I think we can introduce the `high` parameter but forcing parameter names to be explicit (at least for the next release) so that users can be informed of affected codes
```python
def TruncatedNormal(*, loc=0., scale=1., low=None, high=None, validate_args=None):
    base_dist = dist.Normal(loc, scale)
    return TruncatedDistribution(base_dist, low=None, high=None, validate_args=None)

def TruncatedCauchy(*, loc=0., scale=1., low=None, high=None, validate_args=None):
    base_dist = dist.Normal(loc, scale)
    return TruncatedDistribution(base_dist, low=None, high=None, validate_args=None)
```

To get the mean/variance of TruncatedNormal/TruncatedCauchy, I think you can add `mean`/`variance` methods to `LeftTruncatedDistribution` (and probably also for `RightTruncatedDistribution`, `TwoSidedTruncatedDistribution` if you come up with some formula), kind of
```
class LeftTruncatedDistribution(...):
    ...
    @property
    def mean(self):
         if isinstance(self.base_dist, dist.Normal):
              # implement
         elif isinstance(self.base_dist, dist.Cauchy):
              # ...
         else:
              raise NotImplementedError
```

**Comment by MarcoGorelli** [comment]
Thanks @fehiepsi !

So a warning could be added for 0.7.3 which warns that all args of TruncatdNormal will become keyword-only, and then in 0.8.0 the change is enforced?

> To get the mean/variance of TruncatedNormal/TruncatedCauchy,

Sorry, I don't understand - why does this need adding in order to have `high` in `TruncatedNormal`? Or is it a separate enhancement?

**Comment by fehiepsi** [comment]
I guess no need for a warning because Python will inform those argument changes when non-keyword arguments are provided. Regarding mean/variance, currently the LeftTruncated or RightTruncated does not provide mean/variance properties, but we have them in TruncatedNormal and TruncatedCauchy.

**Comment by MarcoGorelli** [comment]
Sorry for the delay, I'll look into this this week
