### ISSUE TITLE
BUG: Automatic reparametrization using handler fails when using discrete latent variable

### ISSUE THREAD

**Issue by corneliusroemer** [pyro-ppl/numpyro#1265]
When a model to be reparametrized using `@numpyro.handlers.reparam(config=reparam_config)` contains a discrete latent variable, I get a `ValueError: Incompatible shapes for broadcasting: ((1, 100), (100, 10))`

According to @fehiepsi this could be a numpyro bug (I assumed it was a coding error at first) (see [forum discussion](https://forum.pyro.ai/t/how-to-avoid-large-number-of-unused-random-variables-in-hierarchical-regression-with-3-levels/3712/13?u=corneliusroemer)

Model code:

```python
reparam_config = {k: LocScaleReparam(0) for k in ["mu"]}

# Reparametrization doesn't seem to work with discrete latent variable
@numpyro.handlers.reparam(config=reparam_config)
def model(school, grade=None):
    sigma = numpyro.sample("sigma", dist.HalfNormal(1))

    n_schools = len(np.unique(school))
    with numpyro.plate("plate_j", n_schools):
        outlier = numpyro.sample("outlier", dist.Bernoulli(0.5))
        mu = numpyro.sample("mu", dist.Normal(outlier, sigma))

    with numpyro.plate("data", len(grade)):
        numpyro.sample("obs", dist.Normal(loc=mu[school], scale=1), obs=grade)

# ValueError: Incompatible shapes for broadcasting: ((1, 100), (100, 10))
```

When I remove the two reparametrization lines, the code works as expected.

Full reproducible notebook is available here as a gist: https://gist.github.com/corneliusroemer/2a8f383ce18bbe53f924c62e5a649731

**Comment by fehiepsi** [comment]
Thanks so much for the reproducible code, @corneliusroemer! It turns out that this behavior is expected. When `mu` has an additional enumerated dimension, you will need to slide over its last dimension:
```python
mu[..., school]  # rather than mu[school]
```

When `reparam` is not used, we are "lucky" that `mu` value still keeps its original shape, hence the code `mu[school]` will work. But it is a better practice to use `mu[..., school]`.

Things will be clearer when you manually reparameterize your model
```python
    ...
    with numpyro.plate("plate_j", n_schools):
        outlier = numpyro.sample("outlier", dist.Bernoulli(0.5), infer={"enumerate": "parallel"})
        mu_base = numpyro.sample("mu_base", dist.Normal(0, 1))
        mu = outlier + mu_base * sigma
```
In this case, `mu_base` will have `plate_j` dimension, but the computation `outlier + mu_base * sigma` will return a result with an additional "outlier"-enumerated dimension. Hence `mu` will have shape `(2, n_schools)`.
