### ISSUE TITLE
[FR] raise missing plate warning in MCMC inference

### ISSUE THREAD

**Issue by martinjankowiak** [pyro-ppl/numpyro#1276]
basically extend #1245 to be enforced more globally

**Comment by fehiepsi** [comment]
I'm a bit hesitating addressing this issue mainly because this will affect a lot of users. It is nice to raise the warning by default but we'll need to incorporate `enable_validation()` mechanism in Pyro and point to it in the warning message so that MCMC users can quickly disable the warning (if they don't like `plate` style and are confident on their models).

**Comment by martinjankowiak** [comment]
well there are different variants for how this might look... for example you could only raise the warning if there's at least one plate (so would catch cases where users are using plates but are doing so incorrectly/inconsistently)

**Comment by fehiepsi** [comment]
> only raise the warning if there's at least one plate

Good idea!!!

**Comment by martinjankowiak** [comment]
you could even have something like `plate_warning in [None, 'strict', 'loose']` with default to `loose`
