### ISSUE TITLE
Can't sample posteior predictive, if model uses no covariates

### ISSUE THREAD

**Issue by sokol11** [pyro-ppl/numpyro#1278]
Hi. I am trying to simulate data using the stochastic volatility model, [described](https://num.pyro.ai/en/stable/examples/stochastic_volatility.html) in the docs. However, when I try to get posterior predictive samples, it just returns observed values. For clarity, here's the model function below:
```
def model(returns):
    step_size = numpyro.sample("sigma", dist.Exponential(50.0))
    s = numpyro.sample(
        "s", dist.GaussianRandomWalk(scale=step_size, num_steps=jnp.shape(returns)[0])
    )
    nu = numpyro.sample("nu", dist.Exponential(0.1))
    return numpyro.sample(
        "r", dist.StudentT(df=nu, loc=0.0, scale=jnp.exp(s)), obs=returns
    )
```
So, when I try to predict after fitting the model:
```
...
predictive = Predictive(model=model, posterior_samples=mcmc.get_samples())
samples_predictive = predictive(random.PRNGKey(42), returns)
```
I just get my observed `returns` back.

Am I doing something wrong? Is there a way to actually forward sample here? Thank you!

**Comment by omarfsosa** [comment]
Hi @sokol11, this is the expected behaviour of the `Predictive` class - it will only give you the predictive samples if you don't pass the observed values (in this case the `returns` variable). The problem is that the number of steps depends on the shape of `returns`. To achieve what you are trying to do, I recommend you refactor a bit. Write your model as
```python
def model(num_steps, returns=None):
    # ...
    s = sample("s", GaussianRandomWalk(step_size, num_steps=num_steps)
    # ...
```
Then for generating the predictive samples:

```python
# ...
predictive = Predictive(model=model, posterior_samples=mcmc.get_samples())
samples_predictive = predictive(random.PRNGKey(42), num_steps=len(returns))
```
Note that the last line does not use the `returns` values, just its size.

Hope this helps!

**Comment by sokol11** [comment]
Thanks @omarfsosa . This makes a lot of sense and worked like a charm. Closing this.
