### ISSUE TITLE
Potential shape bug in mcmc.get_samples()

### ISSUE THREAD

**Issue by sokol11** [pyro-ppl/numpyro#1285]
Reporting a potential bug in MCMC sample / get_samples with unexpected (transposed) shapes returned from the get_samples() call. Here's a reproducible example:
```
from numpyro.examples.datasets import SP500, load_dataset
import numpyro
import numpyro.distributions as dist

_, fetch = load_dataset(SP500, shuffle=False)
dates, data = fetch()

def grw_model(ts_length, data=None):
    """
    Gaussian Random Walk (GRW) log-volatility model with a Student T
    likelihood.
    """
    with numpyro.plate('assets', 1, dim=-1):
        sigma = numpyro.sample('sigma', dist.Exponential(10.))
        h = numpyro.sample(
            'h',
            dist.GaussianRandomWalk(scale=sigma, num_steps=ts_length)
        ).reshape(-1, 1)
        nu = numpyro.sample('nu', dist.Exponential(.1)).reshape(-1, 1)
        y = numpyro.sample(
            'y_pred',
            dist.StudentT(df=nu, loc=0., scale=jnp.exp(h)).to_event(1),
            obs=data
            )
        return y

mcmc = MCMC(NUTS(model), num_warmup=1000, num_samples=1000,
                num_chains=1, chain_method='sequential', progress_bar=True
                )

mcmc.run(random.PRNGKey(42), len(dates), data)
```
 The expected shape of the `h` variable in the posterior is `(n_chains, n dates, n_assets)`. However, when `mcmc.get_samples()` is called, the last two dimensions are switched in the resulting output to `(n_chains,  n_assets, n dates)`. The issue is compounded by the fact that the correct shape is still returned from the predictive call, i.e. 
```
posterior_samples = mcmc.get_samples()
print(posterior_samples['h'].shape
```
incorrectly yields `(n_chains,  n_assets, n dates)`., but
```
predictive = Predictive(model, posterior_samples)
samples_predictive = predictive(random.PRNGKey(42), ts_length=len(dates))
print(samples_predictive['h'].shape
```
correctly yields `(n_chains, n dates, n_assets)`.

This seems innocuous but is actually quite inconvenient, as samples from posterior and posterior_predictive have to be processed differently to reconcile the shape transposition. And the incorrect data shapes can cause the system to run out of RAM and crash, presumably due to dims being incorrectly broadcasted.

**Comment by fehiepsi** [comment]
`(n_chains, n_assets, n dates)` is the expected shape because `dates` is the event dimension of `h` site (see the second point of [this comment](https://forum.pyro.ai/t/shape-issues-with-a-hierarchical-timeseries-model/3755/11?u=fehiepsi)). I'm not sure why Predictive yields `(n_chains, n dates, n_assets)` in your case. What is `posterior_samples` in `Predictive(model, posterior_samples)`?

**Comment by sokol11** [comment]
Thanks @fehiepsi . So, to clarify, the event dimension is always going to be the rightmost?

`posterior samples` in `Predictive(model, posterior_samples)` are `posterior_samples = mcmc.get_samples()`

**Comment by fehiepsi** [comment]
What `reshape` does is to reshape the numpy array, not the distribution. Your code is equivalent to
```
h = numpyro.sample('h', ...)
h = h.reshape(...)
```
If `posterior_samples` in Predictive is obtained from `mcmc.get_samples` then by default, predictive won't return the `h` site (because it already belongs to `posterior_samples`, no need to predict). How can you get `samples_predictive['h']`?

**Comment by sokol11** [comment]
Ah good point about h not being in the `samples_predictive` I am actually returning a transformation of h, which is `v = numpy.deterministic('volatility', jnp.exp(h)`, but same can be said of `y` which is transposed in `posterior_samples` vs `samples_predictive`

**Comment by sokol11** [comment]
> What `reshape` does is to reshape the numpy array, not the distribution. Your code is equivalent to
> 
> ```
> h = numpyro.sample('h', ...)
> h = h.reshape(...)
> ```
> 
> If `posterior_samples` in Predictive is obtained from `mcmc.get_samples` then by default, predictive won't return the `h` site (because it already belongs to `posterior_samples`, no need to predict). How can you get `samples_predictive['h']`?

Is there a way to change the shape of the distribution, e.g., transpose it, without creating an additional deterministic variable?

**Comment by fehiepsi** [comment]
> It seems there is no way to have the (dates x assets) shape returned from the model

Yes, you are right. We don't support batch dimensions on the right of event dimensions. Not sure why you don't want to transpose the data? I read your model and think that you are having a batch (assests) of time series. If you consider your data as 1 single timeseries with `assets` are features at each time step, then you might not use `plate` for `assets` because it is not a batch dimension of your data. You can construct your model as a [timeseries](https://num.pyro.ai/en/stable/tutorials/time_series_forecasting.html) problem in that case (which uses `scan` and `dates` will be the leftmost dimension.

> one expects asset as the rightmost dimension

It is better to think asset as the rightmost **batch** dimension.

> Is there a way to change the shape of the distribution

I'm not sure if we can support it. Probably it is possible so please open a separate FR for it.

**Comment by sokol11** [comment]
Thanks @fehiepsi . I think, ideally, the data orientation (columns vs rows) should be a matter of user preference. In my case I have dates as rows everywhere outside of numpyro, which is why if I transpose the data, I have to transpose it back later on. But I'm sure there is a reason for this restriction on data orientation, as well as the distinction between event_shape and batch_shape, which I don't believe exists in pymc in quite the same way. So transposing data there and back seems like the most logical solution for now.
