### ISSUE TITLE
icdf of beta distribution is not implemented

### ISSUE THREAD

**Issue by ayaka14732** [pyro-ppl/numpyro#1365]
```python
>>> import numpyro.distributions as dist
>>> d = dist.Beta(1, 5)
>>> d.icdf(0.975)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ayaka/venv/lib/python3.10/site-packages/numpyro/distributions/distribution.py", line 463, in icdf
    raise NotImplementedError
NotImplementedError
```

NumPyro version: 0.9.1

**Comment by e-pet** [comment]
I'd like to use the beta icdf in a `pyro.deterministic` statement in a model guide. Do I understand correctly that that is not possible by simply using the scipy function because gradient information is required? (I tried doing so and got errors that seemed to indicate this.) 

Any recommendations for what would currently be the best / easiest way to circumvent this problem? Can I somehow implement and provide the gradient information by myself?

**Comment by fehiepsi** [comment]
I guess if beta icdf is only used at deterministic sites for prediction, then you can use `host_callback` as in [TruncatedDistribution](https://num.pyro.ai/en/stable/tutorials/truncated_distributions.html) tutorial. If it is used at some downstream observation sites, then we need grad rules for it. Please see [this tutorial](https://jax.readthedocs.io/en/latest/notebooks/Custom_derivative_rules_for_Python_code.html) for more information.

**Comment by e-pet** [comment]
(In case somebody else finds this and looks for a solution, I opted to use the Kumaraswamy distribution instead, as recommended in the jax issue linked to above. It's very similar / in some cases identical to the beta distribution and has the icdf implemented.)

**Comment by fehiepsi** [comment]
As suggested in https://github.com/google/jax/issues/2399, we can use `tfp.math.betaincinv` in the implementation of this cdf.

**Comment by fehiepsi** [comment]
This can be added in the same way as #1475 .
