### ISSUE TITLE
Stein-bnn Confidence Interval plot

### ISSUE THREAD

**Issue by caxelrud** [pyro-ppl/numpyro#1422]
I modified the stein_bnn example to include a CI plot.
At this moment, I am using the training data to check the model.
Not knowing the results of the prediction function, I used the several results to create the mean and distribution information and used in the plot.
Is it valid?
Do you recommend another method?  
Attached the jupyter notebook file.
[stein_bnn.zip](https://github.com/pyro-ppl/numpyro/files/8849789/stein_bnn.zip)

**Comment by OlaRonning** [comment]
Hi @caxelrud,

Would you mind uploading your code as a [gist](https://gist.github.com/) and linking it instead of the zip file? Then I'd love to have a look at what you've done.

**Comment by caxelrud** [comment]
I created a gist at:
https://gist.github.com/caxelrud/66288633f771da52c893736e9684d65f

**Comment by OlaRonning** [comment]
@caxelrud, your final plot shows the uncertainty (variance) due to the latent variable (the variance of the Stein particles). If you are interested in the epistemic uncertainty (uncertainty in likelihood term) you should increase the number of samples (`num_samples`) in `Predictive`
``` python
pred = Predictive(
        model,
        guide=stein.guide,
        params=stein.get_params(result.state),
        num_samples=1,  # <---- increase to assess epistemic uncertainity
        batch_ndims=1
    )
```
Feel free to open a PR updating the example with your CI plot.
