### ISSUE TITLE
Make inference utilities available for prediction

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#148]
Related issue - #41. 

It will be nice to provide an easy interface for doing predictions (ideally a vectorized version of `TracePredictive`), so that users do not need to write code to do this by themselves. e.g. [baseball](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/examples/baseball.py#L150). More detailed discussion on the design is needed, and hopefully, we'll have some more insights on this after attempting this in Pyro https://github.com/pyro-ppl/pyro/issues/1725.

**Comment by fehiepsi** [comment]
I think that for many models, we can also make a vectorized version in numpyro by using `vmap` (not sure how to do it in Pyro though).

**Comment by fehiepsi** [comment]
More tasks to complete this issue:

- [ ] Implement predictive for log likelihood. (I wondered if we can store `args`, `kwargs` in mcmc object so that these model-related information can be accessed when we pass `mcmc` object to other library (e.g. arviz))
- [ ] Implement predictive for prior. For this purpose, we can have `num_samples` and allow empty `posterior_samples` as in NumPyro.

**Comment by neerajprad** [comment]
@fehiepsi - I think we can close this issue now?

**Comment by fehiepsi** [comment]
Sure! I'll go for a pass tomorrow to see if we miss any feature for arviz, then will update #349.
