### ISSUE TITLE
The initial value of the run function is invalid.

### ISSUE THREAD

**Issue by t-taichi** [pyro-ppl/numpyro#1539]
In the MCMC class, the folllowing initialization is succeed. It correctly starts from the initial value.
```
                kernel = numpyro.infer.NUTS(
                    model,
                    max_tree_depth=max_tree_depth,
                    init_strategy=init_to_value(values=init_params),
                    target_accept_prob=target_accept_prob,
                )
```
However, the initialization in the run function below does not reflect the initial value.
(Each value of init_params are arrays of chain numbers.)
```
                mcmc.run(
                    jax.random.PRNGKey(1),
                    y=obs,
                    init_params=init_params,
                )
```

**Comment by fehiepsi** [comment]
The `init_params` is meant to be used for `potential_fn` (should we update the docs to better reflect this?), rather than a numpyro `model`. We can modify [this line](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/infer/hmc.py#L652) into something like
```python
new_init_params, ... = ...
init_params = new_init_params if init_params is None else init_params
```
Note that the main difference is `init_params` are samples in unconstrained (real) domain of the `model`, while `init_to_value` happens in the constrained domain of the model.

**Comment by fehiepsi** [comment]
Let us know if you want us to allow using `init_params` for `model`, or to update the docs to reflect that this only takes effect for models with `potential_fn` specified.

**Comment by t-taichi** [comment]
Thank you for your detailed explanation.
I think it is better to allow using init_params for model like as init_to_value.

**Comment by fehiepsi** [comment]
Do you want to make a PR for the change proposed in https://github.com/pyro-ppl/numpyro/issues/1539#issuecomment-1438987752?

**Comment by t-taichi** [comment]
Yes, I hope so.
