### ISSUE TITLE
Python 3.9 broken

### ISSUE THREAD

**Issue by tingiskhan** [pyro-ppl/numpyro#1922]
I noticed that version 0.16.0 breaks Python 3.9 support with [this change](https://github.com/pyro-ppl/numpyro/commit/c110053eb95f5398f11b93ce3efa21de4559012c) with the following error message:
```
  File "/home/..../numpyro/diagnostics.py", line 233, in <module>
    samples: dict | np.ndarray, prob: float = 0.90, group_by_chain: bool = True
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```
The setup.py file still indicates support for Python 3.9, so I assume this is supposed to work?

**Comment by juanitorduz** [comment]
@fehiepsi do you wanna support python 3.9? If we do we can amend these changes but need to make sure we set python 3.9 in https://github.com/pyro-ppl/numpyro/blob/master/.github/workflows/ci.yml#L17 because otherwise we can not catch these type of issues in the test suite. However, I think JAX just supports 3.10 and higher https://github.com/jax-ml/jax/blob/main/setup.py#L119?

**Comment by victor-4p** [comment]
> @fehiepsi do you wanna support python 3.9? If we do we can amend these changes but need to make sure we set python 3.9 in https://github.com/pyro-ppl/numpyro/blob/master/.github/workflows/ci.yml#L17 because otherwise we can not catch these type of issues in the test suite. However, I think JAX just supports 3.10 and higher https://github.com/jax-ml/jax/blob/main/setup.py#L119?

From a user perspective I would only want having python_version>=3.10 in setup.py s.t. I don't install incompatible versions. It seems to be as you say that JAX > 0.4.30 only supports Python 3.10+.
