### ISSUE TITLE
`plate` has unexpected behaviour when dist has batch_shape

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#355]
I faced this issue while revising baseball example using `plate`. The repro code
```
import jax.numpy as np
import numpyro
import numpyro.distributions as dist
from numpyro.handlers import trace, seed

def model():
    with numpyro.plate('plate', 10):
        numpyro.sample('x', dist.Normal(np.zeros(10), 1))

trace(seed(model, 0)).get_trace()['x']['value'].shape
```
should return `(10,)` but currently, it returns `(10, 10)`.

cc @neerajprad

**Comment by neerajprad** [comment]
Thanks for the bug report! We need to handle the interaction between batch and sample shapes better. I'll fix this shortly.

**Comment by neerajprad** [comment]
Hmm..this issue is actually more complicated. Currently we can only change a distribution's shape on the left. If we have a distribution with batch shape `[2, 1, 10]`, we cannot just expand it to some arbitrary batch shape like `[2, 5, 10]`, unlike in Pyro which allows for this using `.expand`. The case above is more easily handled though. I'll address that first.

**Comment by fehiepsi** [comment]
> we cannot just expand it to some arbitrary batch shape

Do you mean that our distribution implementation does not allow this? Typically, I think we can just do `dist.batch_shape = (2, 5, 10)` to "expand" the distribution. I guess we are missing something like
```
shape = broadcast_shapes(self.batch_shape + self.event_shape, value.shape)
value = np.broadcast_to(value, shape)
```
in `distributions` module?

**Comment by neerajprad** [comment]
> I guess we are missing something like

I think doing it in a generic way at the Distribution class level will require us to broadcast parameters (so that other methods like mean also broadcast correctly), but I think it might be harder when distributions have multiple parameterizations or intermediate tensor values. That's the reason why we have an instance level expand in pytorch. Anyways, I don't see the need for this currently.

**Comment by fehiepsi** [comment]
Now, I understand your point. Agreed that we don't need it.
