### ISSUE TITLE
Declare dependent dimensions

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#357]
In Pyro, we can declare dependent dimensions through `.to_event()`. Currently, this is useful for correctly computing log_prob of a transformed distribution where `transform.event_dim>0` but `base_dist.event_shape=()`. In particular, we need this to declare `base_dist` in autoguide.

In Pyro, this is achieved by using Independent class. It seems unnecessary to me. Can we just manipulate `batch_shape`, `event_shape` and correctly compute the returned value for `log_prob`? I think we just need 1 line of code for each distribution
```
def log_prob(...):
    ...
    # event_ndim minus 1 for multivariate distributions
    return sum_rightmost(log_prob, len(self.event_shape))
```

If Independent class turns out to be useful, then we will implement it instead.

**Comment by neerajprad** [comment]
I think following the Pyro pattern here will be more modular. Adjusting the `batch_shape`, `event_shape` inside each distribution will lead to issues like `batch_shape` not matching the shape of distribution parameters which will necessitate all kinds of checks that are avoidable. Using `.to_event` will confine the change to a single class / method. I am happy to implement a version of this.

**Comment by fehiepsi** [comment]
Sure, I didn't follow up with Distribution development from the start so I didn't appreciate much the current design decision. I imagine the method `to_event` can be implemented as
```
def to_event(self, n):
    self.event_shape = self.batch_shape[-n:] + self.event_shape
    self.batch_shape = self.batch_shape[:-n]
```
For some situations such as `loc.shape=(10, 1)`, `scale.shape=(1, 10)`, this still works.

While writing this reply, I do agree that using Independent will be beneficial for functions which utilizes this dependent information. It will take more effort to check how many dependent dims a distribution has (because some are univariate, some are multivariate).

**Comment by neerajprad** [comment]
Np, it is always good to question existing design patterns! Regarding the solution above, it is not that it cannot be done, but this will leak into individual distribution classes (methods like `log_prob`; additionally, if any methods use batch shape in the constructor to do something like set some internal attribute, and we later change batch shape, we will need to also change what was done internally in the constructor). 

This also makes it harder for other user-defined distributions that implement the `Distribution` interface to adhere to because all distribution methods and attributes need to assume that `batch_shape` and `event_shape` are mutable attributes. Therefore any method that makes use of these attributes to set some state may need to be rerun when these are changed. On the other hand, there are no specific design advantages to doing this, as far as I can see. Those are some of the reasons why this was implemented as a composition over an existing distribution instance in both pytorch and tensorflow.

**Comment by fehiepsi** [comment]
Thanks @neerajprad ! Based on your comment, it looks like an effect handler to me. :D
