### ISSUE TITLE
expose submodules to the main namespace

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#371]
NumPyro is lightweight, so submodules live in their own files. Currently, we don't expose those submodules to `__init__`, so only a few submodules are exposed to the main namespace `numpyro`. This in turn leads to a lot of import statements for a numpyro program.

I would propose to expose all submodules to the main namespace for convenience. 

TODOs:
 - [x] Separate out `transforms` into its own module `numpryo.distributions.transforms`. This will align it with Pyro and help keep the generic interface alike.
 - [x] Move SVI and MCMC into `infer` module but make all inference algorithms available from the `infer` namespace.
 - [x] Add infer_util
 - [x] Add diagnostics

**Comment by neerajprad** [comment]
@fehiepsi - I have added some subtasks here. I think it will help to keep distributions, inference algorithms and handlers in their own namespace so as to avoid name collisions. e.g. it seems reasonable to be able to do:
```
from numpyro import distributions as dist, infer, handlers

dist.Normal(..
infer.NUTS(..
handlers.replay(..
```

rather than make each of these classes available for import directly from `numpyro`. WDYT? The above structure also matches the generic API.

**Comment by fehiepsi** [comment]
Sure, that would be very helpful! My proposal is to add
```
import numpyro.infer_util
import numpyro.util
import numpyro.diagnostics
```
to `__init__.py` file so that when I type `numpyro.`, the IDE (& autocompletion) will display out these submodules (together with their docstrings) for me to choose. Currently, typing `numpyro.` only displays some primitives, `patch`, `version`, and `distributions`.
