### ISSUE TITLE
Masking out of support log_prob

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#373]
Several months ago, we decided to not have "masking" pattern when computing log_prob for out-of-support samples. I thought that it was good because we already have a check for invalid samples.

We did so because masking is not necessary for our inference algorithms. Now, given that users will want to use our distributions for something else: e.g. to compute custom log_prob, to plot log_prob, we should have a masking pattern for popular distribution (maybe not for all distribution, to avoid expensive checks such as positive_definite). Currently, Uniform(0, 1).log_prob(-1) will be `0` (instead of `-inf`), which is not desirable.

**Comment by fehiepsi** [comment]
This [gist](https://nbviewer.jupyter.org/gist/fehiepsi/eb3053aad5ece9ee4feba452d22e2740) shows that the distributions have this issue are:
+ Exponential
+ HalfCauchy/HalfNormal
+ TruncatedCauchy/TruncatedNormal
+ Uniform
Masking for these distributions is easy so I think that it is worth to add masks for these distributions.

**Comment by neerajprad** [comment]
> Now, given that users will want to use our distributions for something else: e.g. to compute custom log_prob, to plot log_prob, we should have a masking pattern for popular distribution (maybe not for all distribution, to avoid expensive checks such as positive_definite). Currently, Uniform(0, 1).log_prob(-1) will be 0 (instead of -inf), which is not desirable.

I think the correct solution here should be for us to turn on `validate_args` by default, so that users can catch bugs when they are wrong. Otherwise, this will turn on some validation checks on large tensors by default with no way of turning it off. If a user is confident of their model and wants to run it as fast as possible, it should be possible to not have to do these checks which will be possible by just turning distribution validation check off.
