### ISSUE TITLE
More runtime flexibility in the MCMC class

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#438]
- [ ] Being able to freeze/start the chain from the last state without doing warmup adaptation.
 - [ ] In some cases, users may want to reuse the adapted `step_size` and `mass_matrix` parameters from the first run and do subsequent runs (say on slightly different datasets) without doing `warmup`.

An alternative would be to keep the `MCMC` class simple, and use the `hmc` function directly to get more control over the runs. I think both the above use cases can be supported by directly using the `hmc` class at the cost of writing some additional boilerplate code.

**Comment by fehiepsi** [comment]
I think that we can solve both issues by introducing an additional arg `inverse_mass_matrix` to HMC.__init__() and store the last state of MCMC.

Having `inverse_mass_matrix` arg will also be helpful for the case users to use AutoDiagonalNormal to learn inverse_mass_matrix (which is much faster than using MCMC warmup).

Storing the last state of MCMC is also useful. We can inspect `step_size`, `inverse_mass_matrix` from it without having to use `extra_fields` to store corresponding values from all transitions.

With the last state, we can start MCMC again with
```
mcmc = MCMC(NUTS(..., step_size=last_state.adapt_state.step_size, inverse_mass_matrix=last_state.adapt_state.inverse_mass_matrix))
mcmc.run(..., init_params=last_state.z)
```

**Comment by neerajprad** [comment]
> WDYT about the above proposal?

This will need us to expose those arguments in `HMC.init` and also the `inverse_mass_matrix` argument in `hmc`. I think doing so for the latter function definitely makes sense since that should have the super-set of all functionality we would like HMC to support. 

For the MCMC class (and HMC/NUTS kernels), I am not fully convinced if it is worth introducing too much complexity at this point, if users can directly use the `hmc` function for more control if they so desire (we should definitely document this better for visibility). For instance, they may want to use the step size and mass matrix from the adaptation phase and the z values from the last run. This can be supported by `MCMC` too, but users will need to set `mcmc.num_warmup=0`, store these parameters from the MCMC run, initialize a new kernel with these parameters which will result in recompilation. With the hmc interface, it is as simple as replacing those values in `HMCState` and just using the sample function.

This may be worth supporting within `MCMC` eventually. Currently, I think that the internals of that class are already quite complex due to having to support chaining using `vmap` etc., and it might be worth refactoring before we add too many other responsibilities on to that class.

**Comment by fehiepsi** [comment]
> This will need us to expose those arguments in HMC.init and also the inverse_mass_matrix

Exposing `inverse_mass_matrix` makes sense to me if there is a request for it (otherwise, because I don't use it, making that change is not necessary to me).

> the internals of that class are already quite complex

probably you didn't mean to compare with the complexity of multiprocessing in Pyro. :)) I think that the interface would be stable and I don't foresee any change in the near future. If we need to support something, we just need to create a new method for it.

> users will need to set mcmc.num_warmup=0, store these parameters from the MCMC run, initialize a new kernel with these parameters which will result in recompilation.

Yep, that was what I thought based on the request. To me, it would be simpler than using `hmc`. Of course, I don't want to add complexity to support something I don't use. If it is an internal request, then using `hmc` would be enough (assuming that proper jit is involved to avoid recompilation potential_fn for other datasets).

**Comment by neerajprad** [comment]
This is based on an internal discussion (low priority for now), but I think it will be a useful feature to have.

> Exposing inverse_mass_matrix makes sense to me if there is a request for it

This is relevant only in the context of the current issue, though as you point out, we don't need to do so if we just store the `adapt_state` instead in HMC/NUTS. Of course, if we want to learn the mass matrix using autoguides and use that to adapt the step size, I think we'll need to be able to pass that into `hmc`.

**Comment by fehiepsi** [comment]
This is addressed in #469.

**Comment by tavin** [comment]
So it seems clear how to draw samples in chunks by saving the state along the way, looking at the current [docs](https://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.mcmc.MCMC.post_warmup_state).

Is there any way to pause and resume warmup? Suppose it's not possible to complete warmup in a single method call, due to some externally imposed timeout.

**Comment by fehiepsi** [comment]
Hi @tavin, I think you can use low level api of the kernel to save and load middle states as needed: https://num.pyro.ai/en/stable/examples/stochastic_volatility.html
