### ISSUE TITLE
Improve doc examples

### ISSUE THREAD

**Issue by hzyjerry** [pyro-ppl/numpyro#461]
This may be nitpicking, but I think it would be great if the examples in documents could include all the `import` statements: [example](https://numpyro.readthedocs.io/en/stable/mcmc.html#numpyro.infer.mcmc.hmc)

The reason being:
1. some times it's non-obvious to new users to get things like `from numpyro.infer.mcmc import fori_collect` correct
2. The examples will become much more self-contained, allowing users to directly copy-paste into terminal to play with.

**Comment by fehiepsi** [comment]
@hzyjerry , thanks for pointing it out! Would you like to make a PR for this enhancement? It would be your first PR to NumPyro, and hopefully, there are more after that. ;)

**Comment by hzyjerry** [comment]
Yes, happy to contribute

**Comment by hzyjerry** [comment]
Hmm it seems that these are well-specified in `testsetup` blocks inside the source code
[example](https://numpyro.readthedocs.io/en/stable/_modules/numpyro/infer/mcmc.html#hmc)

Initially, it was a bit inconvenient for me to run the examples. But maybe it's a design decision to hide them from users?

**Comment by neerajprad** [comment]
> Initially, it was a bit inconvenient for me to run the examples. But maybe it's a design decision to hide them from users?

That's right. Many of the imports were several lines long, and were therefore part of the `testSetup` block so that it did not clutter the code example. However, we have reorganized some of the codebase recently which should reduce the number of import lines, and it is worth considering whether we should add it to the visible code block, so that users can just copy/paste these snippets. If there is too much content here, we can do some CSS hacking later to put the imports in a `hide/show` dropdown. :) 

I think, you can just move the imports from `testSetup` into the test block for now and we can determine later if we need to do customize the CSS.

**Comment by neerajprad** [comment]
Btw..you should be able to run the doc tests using `make doctest`.

**Comment by neerajprad** [comment]
I am closing this. @hzyjerry - feel free to open new issues if you find things lacking in the documentation, or anything that can be improved further.
