### ISSUE TITLE
Incorperating NUTS into larger jittable function

### ISSUE THREAD

**Issue by Joshuaalbert** [pyro-ppl/numpyro#644]
I'd like to use NUTS to perform inference as a small subpart of a larger call. I'd like the whole thing to be jit compilable for maximal performance. Is this possible with numpyro, specifically with NUTS?

**Comment by fehiepsi** [comment]
Yes, it is possible. Sometimes, I do things like
```
def nuts_fit(rng_key, data):
    mcmc = MCMC(NUTS(model), ...)
    mcmc.run(data)
    return mcmc.get_samples()

jit_nuts = jax.jit(nuts_fit)
```
then reuse `jit_nuts`. Does it solve your usage case?

**Comment by Joshuaalbert** [comment]
Thanks for the fast reply! Yes, that's perfect. I should have tried it before asking, but thought better to ask in case others have similar questions. Followup question: What things in numpyro are not jittable?

**Comment by fehiepsi** [comment]
Haha, I think JAX devs should answer that question. AFAIK, some utilities in [diagnostic](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/diagnostics.py) are not jittable because that module uses `numpy` instead of `jax.numpy` to calculate the statistics. We use `numpy` there because we think that users will want to calculate them outside of `jit` context (to avoid the small overhead of JAX). If users request, we can change them to `jax.numpy` without problems. Do you observe anything else?
