### ISSUE TITLE
NumPyro pegs CPU cores after sampling completes

### ISSUE THREAD

**Issue by fonnesbeck** [pyro-ppl/numpyro#659]
I'm running a relatively simple model in NumPyro:

```python
def park_bias_model(y):

    m_mu = numpyro.sample('m_mu', dist.Normal(loc=y.mean(), scale=5))
    s_mu = numpyro.sample('s_mu', dist.HalfNormal())
    mu = numpyro.sample('mu', dist.TransformedDistribution(
        dist.Normal(loc=jnp.zeros(hand_pitch_ids.shape[0]), scale=1),
        AffineTransform(m_mu, s_mu)))

    theta = mu[hand_pitch_ind]
    sigma = numpyro.sample('sigma', dist.HalfNormal())
    numpyro.sample('y', dist.Normal(loc=theta, scale=sigma), obs=y) 
```

Which completes sampling in a few seconds on my local machine. However, I notice that the cores (4) on my machine remain pegged at 100% even after sampling completes. Running a subsequent task, such as getting the mcmc samples, or sampling again, results in a hang of the Python session. Anyone seen this behavior before? I get similar behavior when I run on Colab.

Running version 0.2.4 (Jax version 0.1.72) on Debian with Python 3.8.2.

**Comment by neerajprad** [comment]
Thanks for trying out numpyro! I haven't seen such an issue before. Do you find python hanging when running any of the existing examples, say `python examples/baseball.py`? Another thing to note is that due to JAX's [asynchronous dispatch](https://jax.readthedocs.io/en/latest/async_dispatch.html), it is possible that the sampling isn't finished. To see if that's the case, you can add `mcmc.print_summary()` which will wait for the results to be available before printing it on to the screen. If it is some other cause, and you could share the link to the colab notebook, I will take a look.

**Comment by nkaimcaudle** [comment]
I think it's the same misunderstanding I encountered when using NumPyro initially, #492. JAX returns control to Python before it has finished execution.

**Comment by fonnesbeck** [comment]
I think you are right, thanks. I will close this.
