### ISSUE TITLE
Use multipledispatch for `kl_divergence`

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#762]
As @fritzo's suggestion in https://github.com/pyro-ppl/numpyro/pull/748, we can use `multipledispatch` to simplify dispatching work in `kl_divergence` (and possibly in `biject_to` too?). We can do this when `funsor` becomes the main dependency of numpyro.

**Comment by fritzo** [comment]
For `biject_to` you could simply use Python 3's builtin [singledispatch](https://docs.python.org/3/library/functools.html#functools.singledispatch) which requires no extra dependencies. We use that in Funsor for single dispatch. We had avoided that in PyTorch because PyTorch originally supported Python 2 which is missing `singledispatch`.

**Comment by fehiepsi** [comment]
Thanks for reviewing, @fritzo!
