### ISSUE TITLE
svi.get_params results interpretation

### ISSUE THREAD

**Issue by caxelrud** [pyro-ppl/numpyro#830]
Hi,
From _https://fehiepsi.github.io/rethinking-numpyro/04-geocentric-models.html_ , Code 4.28 trains the model _flist_ and gets parameters using:
p4_1 = svi.get_params(state)

p4_1 has the value:
{'auto_loc': DeviceArray([154.60706  ,  -1.6973906], dtype=float32)}

What is the interpretation of this result?
Thanks!

**Comment by fehiepsi** [comment]
@caxelrud It is the parameter of the autoguide [AutoLaplaceApproximation](http://num.pyro.ai/en/stable/autoguide.html#autolaplaceapproximation). Laplace approximation does MAP inference. The parameter `auto_loc` is the MAP value. FYI, in the next release, you can just simply use [svi.run](http://num.pyro.ai/en/latest/svi.html#numpyro.infer.svi.SVI.run) instead of `lax.scan` or `lax.fori_loop` like that tutorial.

You can ask questions like this on that page (there is a comment section under it) or on the [forum](https://forum.pyro.ai/).
