### ISSUE TITLE
OverflowError: cannot convert float infinity to integer using HMCGibbs

### ISSUE THREAD

**Issue by gcgibson** [pyro-ppl/numpyro#889]
Hi all,

It's so cool that you got marginalizing discrete parameters out! Very nice. I'm wondering if there is any way to extract some summary metrics like there is in pyro. My discrete latent parameter is interpretable so it would be awesome to get some info on it.

Thanks!

**Comment by fehiepsi** [comment]
Hi @gcgibson, please follow the issue https://github.com/pyro-ppl/numpyro/issues/770. In the meantime, you can use [DiscreteHMCGibbs](http://num.pyro.ai/en/latest/mcmc.html#numpyro.infer.hmc_gibbs.DiscreteHMCGibbs), which does HMC-with-Gibbs (instead of enumeration) and will give discrete samples when you run MCMC.

**Comment by gcgibson** [comment]
Hi @fehiepsi ,

I tried the DiscreteHMCGibbs and I'm getting, 

OverflowError: cannot convert float infinity to integer


On the exact same model that works with marginalizing out the discrete parameter.

Any insight?


Casey

**Comment by fehiepsi** [comment]
Interesting! I couldn't find a suspected line of code. Could you make a reproducible code?

**Comment by gcgibson** [comment]
@fehiepsi Hi!

Here is the smallest nugget of my model that I could pull out. 

https://github.com/gcgibson/cfr_numpyro/blob/main/test.py.ipynb

Hopefully that works for you. If it doesn't can you lmk and I will attempt a smaller example?

**Comment by fehiepsi** [comment]
@gcgibson It seems that there is a typo in your code at the discrete site `offset`. There, you set `obs=20` by accidentially I believe. FYI, JAX does not support dynamic size in a model, so something like `B_local[offset:]` will not work when `offset` is not a concrete scalar. A solution is to keep the array as-is and use `mask` handler, like this
```python
        offset = numpyro.sample('offset', dist.Categorical(probs=jnp.repeat(1./20, 20)))  # typo
        y_hat_lagged = jnp.roll(y_hat, offset)
        d_hat = y_hat_lagged + jnp.dot(jnp.array(B_local), b_raw)
        mask = jnp.arange(d_hat.shape[0]) >= offset
        numpyro.sample('d_obs', dist.Normal(d_hat, sigma2).mask(mask), obs=obs_deaths)
```

**Comment by gcgibson** [comment]
Hi @fehiepsi , 

I don't totally understand why that is a typo? I'm looking for a discrete uniform over the integers 1 through 20. Is that incorrect?

**Comment by fehiepsi** [comment]
In your code, there are 3 numbers 20 at the end of that line. The last one is the data (obs). If you need discrete uniform from 1 to 20, you also need to plus 1 to the offset.

**Comment by gcgibson** [comment]
@fehiepsi  I misunderstood then, I thought that was the dimension of the vector [1,20]. If I remove that extra 20 I get 

AssertionError: Missing plate statement for batch dimensions at site y_obs

**Comment by gcgibson** [comment]
FYI, I changed it to the format in the HMM example and now it works!

**Comment by gcgibson** [comment]
@fehiepsi 

I did, if you check out the updated doc you will see it is using offset correctly now. 

https://github.com/gcgibson/cfr_numpyro/blob/main/test.py.ipynb

But the DiscreteHMCGibbs is still throwing the same error.

**Comment by fehiepsi** [comment]
Hmm, that statement, will draw a random categorical value, using a fixed rng_key, so it will be a constant value. In my comment above, I already fixed that typo. You need to use `numpyro.sample` primitive as in other statement. Could you double check?

**Comment by gcgibson** [comment]
If I set it to a regular `numpyro.sample` I get invalid `batch size` for `y_obs`. 

Thanks for working on this!

**Comment by fehiepsi** [comment]
I just test it again. The inference works in my case with
```
lag_mask = jnp.arange(obs_deaths.shape[0]) >= offset
```
I'm not sure why you use `num_data` there at that line. It is different from the code that I posted above. Do I miss something?

**Comment by gcgibson** [comment]
I have that just for forecasting (where obs_death = None). 

How about I close this issue, see if I can fix it and if I can't I'll come up with a smaller reproducible example?

**Comment by fehiepsi** [comment]
I see. I think you can put it in an `if/else` statement like what you already have in your code. The issue here is:
```
dist.Normal(jnp.zeros(10), jnp.ones(10)).mask(jnp.ones(20))
```
will not work because the shape of `dist.Normal(jnp.zeros(10), jnp.ones(10))` is `(10,)` while the shape of `mask` is `(20,)`. It is strange that you still see the issues after that fix. I used the same code as yours... (though haven't run predictions yet)

**Comment by gcgibson** [comment]
Could it be a numpyro or jax version issue? I have numpyro installed via bleeding edge on github and 

```
jax==0.2.8
jaxlib==0.1.59
```

**Comment by gcgibson** [comment]
I have updated the example to not even use the categorical R.V. `offset` and I still get the plate issue FWIW.

**Comment by fehiepsi** [comment]
@gcgibson Here is the [notebook](https://nbviewer.jupyter.org/gist/fehiepsi/bac961f171efb29fa8fa4a2a7ba9dddc) that runs in my system. The inference works with your code, and I moved the mask to `if/else` logic to make prediction work. Could you please double-check?

> not even use the categorical R.V. offset

If there is no discrete latent variable, you should use NUTS instead of DiscreteHMCGibbs. `DiscreteHMCGibbs` does not work for models without discrete latent variables. Does this explain your observation?
