### ISSUE TITLE
Support for TruncatedDistribution

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#895]
Currently, we have one-side truncated normal and cauchy implemented. But it would be nice to add a general class, which uses `cdf` method, for other distributions. There is a [nice discussion here](https://github.com/probtorch/pytorch/pull/121) for context on relevant numerical issues.

cc @fritzo

**Comment by fritzo** [comment]
Note we also have the one-sided general `FoldedDistribution` in Pyro, which is a cheap rsample-friendly qualitatively similar alternative to `TruncatedDistribution`. This doesn't get us any closer to literally translating Stan models, but maybe we can take license to approximately translate models and e.g. check that we're only slightly truncating, or not truncating past the median (since `Folded` and `Truncated` differ for severely truncated distributions).
