### ISSUE TITLE
Cannot serialise MCMC object

### ISSUE THREAD

**Issue by AndreRoehrig** [pyro-ppl/numpyro#954]
I get the following error message when I try to pickle a mcmc object after mcmc.run(...):

```
AttributeError: Can't pickle local object 'hmc.<locals>.init_kernel'
```

Is this the expected behaviour? Is there another way of serialising mcmc objects?
I'm using version 0.5.0

**Comment by RaulPL** [comment]
You can save posterior samples and related information with [ArviZ](https://arviz-devs.github.io/arviz/) using  [from_numpyro](https://arviz-devs.github.io/arviz/api/generated/arviz.from_numpyro.html#arviz.from_numpyro), this will create an  InferenceData object and with [to_netcdf](https://arviz-devs.github.io/arviz/api/generated/arviz.to_netcdf.html) you can store it.

What kind of information would you like to save?

**Comment by fehiepsi** [comment]
I would recommend @RaulPL's solution. Alternatively, you can clean up some attributes of the sampler
```python
mcmc.sampler._sample_fn = None
mcmc.sampler._init_fn = None
mcmc.sampler._postprocess_fn = None
mcmc.sampler._potential_fn_gen = None
mcmc._cache = {}
```
We can add [cleanup](http://docs.pyro.ai/en/stable/mcmc.html#pyro.infer.mcmc.mcmc_kernel.MCMCKernel.cleanup) method to optionally clear those cached functions so that you can pickle the `mcmc` object. But using `arviz` would be a better option.
